<?php
/*
 * Simple Child Theme generated by Ultimatum Framework
*/
/**
 * Enqueue scripts and styles
 */

function themes_scripts() {
	wp_enqueue_style( 'theme-stylesheet', get_stylesheet_uri() );
	wp_enqueue_script( 'script-name', get_stylesheet_directory_uri() . '/js/script.js', array(), '1.0.0', true );
}
add_action( 'wp_enqueue_scripts', 'themes_scripts' );

/**
 *
 */